export const commonText={
    turnYourIdeasIntoReality  :"Turn your ideas into reality.",
     attractiveoffersFromTheCommunity :"   Start for free and get attractive offers from the community",
     loginToYourAccount :"     Login to your Account",
     goingOnWithYourBusiness :" See what is going on with your business",
     rememberMe:"Remember Me",
     forgotPassword:"Forgot Password?",
     login:"Login",
     signUp:"Sign Up",
     notRegisteredYet:"Not Registered Yet?",
     createAnAccount:" Create an account",
     invalidEmailAddress:"Invalid email address",
     emailIsRequired:"Email is required",
     passwordMustBeAtleastCharacters:"Password must be at least 6 characters",
     passwordIsRequired:"Password is required",
     passwordsMustMatch:"Passwords must match",
     confirmPasswordIsRequired:"Confirm password is required",
     password:"password",
     loading:"Loading...",
     loginLoading:"login......",
     anErrorOccur:"An error occurred",
     loginFailedTryAgain:"login failed try again",
     loginSuccessfully:"login successfully",
     userRegesteredSuccessfully:"User Regestered successfully",
     regestrationFailed:"regestration failed failed try again",
     User:"user",
     strict:"Strict",
     token:"token"
}

export const dashBoardText={
     productStatistics:" Product Statistics",
     totalSales:"Total Sales",
     productsSold:"  Products Sold",
     averagePrice:"  Average Price",
     productPrice:"Product Price",
     productPrices:"Product Prices",
     averageRate:"$20"
}

export const generatedOrderText={
     currentOrders:"Current Orders",
     generateOrder:"Generate Order",
     orderDetails:"Order Details",
     clearOrders:"Clear Orders",
     productDetails:"Product Details",
     name:"Name:",
     price:"Price:",
     status:"Status:",
     noOrdersYet:"No orders yet",
     orders:"orders",
     OrderGenerated:"Order generated!",
     productCodeDoesNotMatch:"Product code does not match any available product.",
     pleasePasteTheProductCode:"Please paste the product code.",
     processing:"Processing",
     selectedProduct:"selectedProduct"
}
export const invoiceText={
     orders:"orders",
     invoice:"invoice",
     currentOrders:"Current Orders",
     thankYouForYourPurchase:"Thank you for your purchase!",
     date:" Date:",
     code:"Code:",
     status:"Status:",
     total:"Total: $",
     printInvoice:"  Print Invoice",
     dollar:"$",
     _blank:"_blank"
}
export const productsText={
     products:" Products",
     copyToClipboard:"Copy to Clipboard",
     dollar:"$",
     selectedProduct:"selectedProduct",
}
export const listDataText={
     earBurds:"earBurds",
     cocaCola:"cocaCola",
     powerTool:"powerTool",
     ketchUp:"ketchUp",
     wifiRouter:"wifiRouter",
     Camera:"Camera",
     sugerLess:"sugerLess",
     skinCare:"skinCare",
     choclate:"choclate",
     headphone:"headphone",
     Oats:"Oats",
     velo:"velo",
     milk:"milk",
     beautyProduct:"beautyProduct",
     PROD_A:"PROD_A",
     PROD_B:"PROD_B",
     PROD_C:"PROD_C",
     PROD_D:"PROD_D",
     PROD_E:"PROD_E",
     PROD_F:"PROD_F",
     PROD_G:"PROD_G",
     PROD_H:"PROD_H",
     PROD_I:"PROD_I",
     PROD_J:"PROD_J",
     PROD_K:"PROD_K",
     PROD_L:"PROD_L",
     PROD_M:"PROD_M",
     PROD_N:"PROD_N",
}